<a href="https://colab.research.google.com/github/vikasrkarjigi/realtime-stock-analytics-kafka/blob/main/stock_data_ingestion_and_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import yfinance as yf
import pandas as pd
from datetime import date
from IPython.display import display

# Define tickers and company names
tickers = {
    'NVDA': 'NVIDIA',
    'TSLA': 'Tesla',
    'META': 'Meta',
    'AMZN': 'Amazon',
    'AAPL': 'Apple',
    'NFLX': 'Netflix',
    'GOOGL': 'Google'
}

# List to collect all rows
all_data = []

# Fetch and process stock data
for ticker, company_name in tickers.items():
    stock = yf.Ticker(ticker)
    # hist = stock.history(period='1mo')
    hist = stock.history(start='2023-04-01', end=str(date.today()))

    for index, row in hist.iterrows():
        all_data.append({
            'Date': index.date(),
            'Open': row['Open'],
            'High': row['High'],
            'Low': row['Low'],
            'Close': row['Close'],
            'Volume': row['Volume'],
            'Company Name': company_name
        })

# Create DataFrame at once â€” no warnings, faster
result_df = pd.DataFrame(all_data, columns=['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Company Name'])

# Show result
result_df.head()
# display(result_df)
# result_df[result_df['Company Name']== 'NVIDIA']

,Date,Open,High,Low,Close,Volume,Company Name
0,2023-04-03,27.491148,27.981829,27.318260,27.946852,398716000.0,NVIDIA
1,2023-04-04,27.947846,27.981825,27.289274,27.435179,368592000.0,NVIDIA
2,2023-04-05,26.811588,26.980477,26.377869,26.863554,515015000.0,NVIDIA
3,2023-04-06,26.566744,27.062422,26.409846,27.019451,397654000.0,NVIDIA
4,2023-04-10,26.805590,27.603073,26.651691,27.561100,395279000.0,NVIDIA

In [ ]:
result_df.isnull().sum()

Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Company Name    0
dtype: int64

In [ ]:
result_df.to_csv('stock_data_april2023_to_today.csv', index=False)